- Topan/5-10-18/Exercise1/Exercise1a.java
- Topan/5-10-18/Exercise1/Exercise1b.java
- Topan/5-10-18/Exercise1/FirstProg.java
- Topan/5-10-18/Exercise2/Exercise2a.java
- Topan/5-10-18/Exercise2/GasolineReceipt.java
- Topan/5-10-18/Exercise4/EscapeSequencesComments.java
> Add Exercise 1,2,4a

- Fauzi/5-10-2018/EscapeSequenceComments.java
- Fauzi/5-10-2018/FirstProg.java
- Fauzi/5-10-2018/GasolineReceipt.java
- Fauzi/5-10-2018/exercise1/Exercise1a.java
- Fauzi/5-10-2018/exercise1/Exercise1b.java
- Fauzi/5-10-2018/exercise2/Exercise2a.java
- Fauzi/5-10-2018/log5-10-2018.txt
> buka log5-10-2018.txt

- Sahdan/Jum'at-05-Oktober-2018/Exercise 1/Exercise1DrillA.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 1/Exercise1DrillB.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 1/FirstProg.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 2/Exercise2DrillA.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 2/GasolineReceipt.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 4/EscapeSequencesComments.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 4/Exercise4DrillA.java
- Sahdan/Jum'at-05-Oktober-2018/Exercise 4/Exercise4DrillB.java
Add Exercise 1, 2 and 4 by Sahdan...
> Brach by Sahdan

- Wawan/mulai-latihan/Exercise1/Exercise 1A/Exercise1A.java
- Wawan/mulai-latihan/Exercise1/Exercise 1B/Exercise1B.java
- Wawan/mulai-latihan/Exercise1/FirstProg.java
- Wawan/mulai-latihan/Exercise2/Exercise 2A/Exercise2A.java
- Wawan/mulai-latihan/Exercise2/GasolinReceipt.java
- Wawan/mulai-latihan/Exercise4/EscapeSequencesComments.java
- Wawan/mulai-latihan/Exercise4/GasolinReceipt.java
> Wawan setiawan

- Nispi/5-10/EscapeSequenceComment.java
- Nispi/5-10/Exercise1B/Exercise1B.java
- Nispi/5-10/Exercise2A/Exercise2A.java
- Nispi/5-10/FirstProg.java
- Nispi/5-10/GasolineReceipt.java
- Nispi/5-10/exercise1A/Exercise1A.java
- Nispi/5-10/log1.txt
> add exercise 1,2 dan 4

- Resi/Jumat-05-Okt-2018/Exercise 1/FirstProg.java
- Resi/Jumat-05-Okt-2018/Exercise 1/drils 1/Exercise1a.java
- Resi/Jumat-05-Okt-2018/Exercise 1/drils 2/Exercise1b.java
- Resi/Jumat-05-Okt-2018/Exercise 2/GasolineReceipt.java
- Resi/Jumat-05-Okt-2018/Exercise 2/drills 1/Exercise2a.java
- Resi/Jumat-05-Okt-2018/Exercise 4/EscapeSequenceComments.java
> Add Exercise 1,2,4

- Resi/DaftarBiodata.txt
> Biodata Resi

- Wawan/BiodataWawan.txt
> commit BiodataWawan

- Roi/DaftarBiodataRoi.txt
> Add Biodata Roi

- Tugas/DaftarBiodata.txt
> Daftar Biodata

- Wawan/Basic Mysql.txt
> tambah basis data

- Nispi/9-10/sql.txt
> Sql Basic,subquery,join

- Anisa/09 Okt 2018/querySQL.txt
> Query Anissa

- Nispi/10-10/SQQL.txt
> Latihan Sql tgl 10-10-18

- Fauzi/10-10-2018/latihanSQL2.txt
> latihan sql2

- Wawan/Rabu, 10-10-2018/Query Lanjutan.txt
> Tambah SQL Query

- Sahdan/Rabu-10-Oktober-2018/Sahdan_SQL_10-Okt-2018.txt
> SQL fase 2 sahdan

- Fauzi/10-10-2018/latihanSQL2.txt
> lanjutan latihan tanggal 10-10-2018

- Tugas/Soal-SoalSQL/Soal Query Wawan.txt
> Soal Dari Wawan

- Tugas/Soal-SoalSQL/SOALNISPI.txt
> Soal Sql Nispi

- Tugas/Soal-SoalSQL/soal_MZada.txt
> soal sql Z

- Tugas/Soal-SoalSQL/SoalFauzi.txt
> 4 soal query

- Fauzi/11-10-2018/laihanQuery3.txt
- Fauzi/12-10-2018/laihanQuery4.txt
> Latihan sql part 3

- Nispi/11-10/JawabSqlNispi.txt
- Nispi/12-10/JawabSqlNispi.txt
Menjawab soal Sql dari teman-teman
> Jawab Sql Nispi
